### ISSUE TITLE
support for activerecord 6?

### ISSUE THREAD

**Issue by 34code** [cockroachdb/activerecord-cockroachdb-adapter#34]
Using rails 6.0.0.rc1 and I get the following on install:

```Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    activerecord-cockroachdb-adapter (~> 0.2) was resolved to 0.2.2, which depends on
      activerecord (~> 5.1, >= 5.1.1)

    rails (~> 6.0.0.rc1) was resolved to 6.0.0.rc1, which depends on
      activerecord (= 6.0.0.rc1)```

**Comment by Joseph94m** [comment]
This does not only affect ActiveRecord but also rails and railties. Upgrading to rails and railties 6.0.0 require ActiveRecord 6.0.0 which is not compatible with  activerecord-cockroachdb-adapter 0.2.3....

**Comment by jordanlewis** [comment]
We're going to be adding support for Rails 6 soon.

**Comment by mtparet** [comment]
Any news on this issue ? (ie: when cockroachdb will work without major issue under Rails :) )

**Comment by kenliu** [comment]
We've released an updated [beta version of our ActiveRecord adapter](https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions/5.2.0.beta2) with ActiveRecord 5.2+ support. Would welcome any testing and feedback here!

**Comment by Piioo** [comment]
The problem is we need ActiveRecord 6 support. The release date was August 16, 2019....

I would build in this adapter to new applications, but I do not want to use old Rails....so...

**Comment by kenliu** [comment]
We've released the [ActiveRecord adapter](https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions/5.2.0), which supports ActiveRecord 5.2+ (including ActiveRecord 6). We would welcome any feedback on this new version.

**Comment by Dimo-iz** [comment]
I see that this issue was closed but I just installed activerecord-cockroachdb-adapter v5.2.0 and there is still get the same problem when using Rails 6 and ActiveRecord 6.0.3.2

**Comment by Piioo** [comment]
@kenliu , have you tried it?

I get this with a completely new application.
```
Resolving dependencies...
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    activerecord-cockroachdb-adapter (~> 5.2.0) was resolved to 5.2.0, which depends on
      activerecord (~> 5.2)

    rails (~> 6.0.3, >= 6.0.3.2) was resolved to 6.0.3.2, which depends on
      activerecord (= 6.0.3.2)
```

May you change the dependencies in https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/master/activerecord-cockroachdb-adapter.gemspec#L16

**Comment by Piioo** [comment]
And when I remove the requirement in the gemspec I got this with rails 6:

```
=> RAILS_ENV=test bundle exec rails db:drop db:create db:load:schema
rails aborted!
NoMethodError: undefined method `async_exec' for nil:NilClass
/Users/pisz/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
```

**Comment by rafiss** [comment]
Our mistake -- we'll keep this open and try to schedule work for this.

**Comment by Piioo** [comment]
Every 3 years a new Rails version come out. The release date of Rails 6 was August 16, 2019.

Will you be able to write an adapter for Rails 6 or shouldn't we have any hope?

**Comment by vy-ton** [comment]
We are actively working on the Rails 6 upgrade and will post here once we have a version to try

**Comment by vy-ton** [comment]
@Piioo @Dimo-iz @mtparet @Joseph94m @34code 
We now have a [beta release](https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions/6.0.0beta2) of an adapter that supports Rails 6.0.3, please check it out and file any issues you discover. Thanks for continuing to voice your support for developer tools you would like to see supported.

**Comment by Piioo** [comment]
Thanks @vy-ton it seams to work.

**Comment by rafiss** [comment]
Hi all, thanks for your patience. We just released full support for Rails 6.0 https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions/

Try it out and please file any issues you encounter!
